### ISSUE TITLE
希望增加AMLL TTML数据库已有歌词的检索功能

### ISSUE THREAD

**Issue by SteamFinder** [Steve-xmh/amll-ttml-tool#13]
希望能增加已有歌曲歌词的检索功能，避免出现重复提交歌词，同时便于歌词制作者查阅

另：可否AMLL在调用AMLL TTML DB的歌词时，在适当的位置（例如歌词末尾等等）显示该TTML歌词的制作者或其他信息
给予歌词作者一些成就感的同时能够更好发挥积极性，同时也让AMLL的使用者了解并参与进来，共建歌词库

**Comment by Steve-xmh** [comment]
已支持
