### ISSUE TITLE
AMLL TTML Database的新提交歌词审核问题

### ISSUE THREAD

**Issue by SteamFinder** [Steve-xmh/amll-ttml-tool#15]
新提交的歌词是暂时停止审核了吗
Pull Request里许多歌词提交请求都等待审阅，甚至有九月份的歌词积压未合并

**Comment by Steve-xmh** [comment]
是这样，因为个人时间精力缘故抽不出时间看歌词，其他人情况大概也是如此
毕竟整歌词是个人兴趣爱好，但没办法一直稳定的做下去，兴致没了就不好继续下去了
如果有意向帮助审核的话可以邮箱联系我
