### ISSUE TITLE
[Bug反馈] 一个关于吞编辑的 Bug

### ISSUE THREAD

**Issue by MianSoft** [Steve-xmh/amll-ttml-tool#16]
触发过程: 我在打轴页下打了轴, 切到编辑页对歌词进行编辑后感觉不满意进行了撤回操作, 回到打轴页发现我之前打了一半的轴直接对我进行一个撒由那拉八八六 😡
![动画](https://github.com/Steve-xmh/amll-ttml-tool/assets/56493273/42a80ff6-d83e-4a03-a78d-481d0b3bf768)
(此处有一个GIF, 轴的内容是为了展示 Bug 随便找了个搞笑视频)

**Comment by MianSoft** [comment]
哦,忘了,在使用` 顶部栏 - 工具 - 使用简单方式对歌词行分词 `时也能触发这个问题

**Comment by Steve-xmh** [comment]
已提供记录打轴操作供撤销使用功能

**Comment by MianSoft** [comment]
好好好
