### ISSUE TITLE
TTML Tool 似乎无法为一个歌词行中只有一个单词的歌词添加时间戳

### ISSUE THREAD

**Issue by Havenmab** [Steve-xmh/amll-ttml-tool#17]
（多图警告）在使用TTML Tool为只有一个单词的歌词行打轴之后，保存歌词文件再重新打开，记录的时间戳会消失（0:00.000）。在AMLL中表现为歌词未滚动到这一行时，歌词就已经亮起了。
对于背景人声同样有此问题。
请看VCR：
（GIF）
![PixPin_2024-02-18_02-52-22](https://github.com/Steve-xmh/amll-ttml-tool/assets/72502111/98b06f03-3e74-4499-833a-b10126794a25)

在AMLL中表现为这样（一直亮起）：
![PixPin_2024-02-18_02-19-29](https://github.com/Steve-xmh/amll-ttml-tool/assets/72502111/f811c186-ce38-495d-b0ef-af82431570e9)

查看ttml文件可知，这个单词缺失span标签：
![PixPin_2024-02-18_02-45-08](https://github.com/Steve-xmh/amll-ttml-tool/assets/72502111/71f95bad-6565-4496-8ac0-e7971c8e9a75)

修正方法：手动在ttml文件中为这个单词添加span。
![PixPin_2024-02-18_02-47-42](https://github.com/Steve-xmh/amll-ttml-tool/assets/72502111/64cf1dac-62a0-44e4-b64c-0dd489455632)

修正后的效果（可以正常逐词）：
![PixPin_2024-02-18_02-51-01](https://github.com/Steve-xmh/amll-ttml-tool/assets/72502111/9f1db0a2-c269-45b2-8da9-85f45fe9a43b)

**Comment by Steve-xmh** [comment]
问题已修正
