### ISSUE TITLE
[bug]所有单词时间戳均为00:00.000

### ISSUE THREAD

**Issue by Havenmab** [Steve-xmh/amll-ttml-tool#18]
使用版本：
![PixPin_2024-02-21_22-16-48](https://github.com/Steve-xmh/amll-ttml-tool/assets/72502111/9a6cf257-9c7e-4d18-854a-d132c4bafa82)

bug描述：所有单词的时间戳（span元素）均为00:00.000。这导致AMLL中歌词无法正常滚动。

请看VCR：
![PixPin_2024-02-21_22-11-10](https://github.com/Steve-xmh/amll-ttml-tool/assets/72502111/4369b99e-432b-48f0-870f-d1f8a8995f3a)

**Comment by Steve-xmh** [comment]
已修正
