### ISSUE TITLE
关于从Apple Music获取歌词

### ISSUE THREAD

**Issue by Heathcliff-Zhao** [Steve-xmh/amll-ttml-tool#19]
您好！
我看计划中写道“从 Apple Music 中获取 Apple Syllable 逐词歌词”，想请教一下是如何实现的。
请问您的方法是基于Apple官方的歌词api吗？还是用了一些更加复杂的方式呢？
感谢您的时间！

**Comment by Steve-xmh** [comment]
届时会完成的，还请敬请期待
