### ISSUE TITLE
[Enhancement]一种新的歌词下载方式

### ISSUE THREAD

**Issue by chengnan049** [Steve-xmh/amll-ttml-tool#28]
https://github.com/glomatico/gamdl 该工具可以从 Apple Music 获取 TTML，不过会面临 DMCA 问题

**Comment by Steve-xmh** [comment]
已经有内定的其他方法获取 Apple Music 的 TTML 歌词文件，且这个仓库的语言与咱们这个不匹配，所以最多做参考用途，之后会把类似的功能安排上的
