### ISSUE TITLE
[BUG反馈] 网页端TTML Tool无法同时保存对唱人声+背景人声的设置

### ISSUE THREAD

**Issue by ITManCHINA** [Steve-xmh/amll-ttml-tool#29]
# BUG描述
在我提交一份[歌词](https://github.com/Steve-xmh/amll-ttml-db/pull/1465)的时候发现，通过网页端TTML Tool导出的歌词（无论是上传到数据库，还是保存ttml文件到本地）都会出现一个问题：当一行歌词同时被设定为`背景人声`和`对唱人声`的时候，文件导出后会丢失`对唱人声`的设定。如图所示
![1719825575397](https://github.com/Steve-xmh/amll-ttml-tool/assets/50987405/b056cc2f-3bfd-41ff-93bf-02486136536a)
![1719825599747](https://github.com/Steve-xmh/amll-ttml-tool/assets/50987405/13a54a0d-05c7-40ba-896e-18b544984e94)

# 我期望达成的样式
![1719826275379](https://github.com/Steve-xmh/amll-ttml-tool/assets/50987405/258754ce-1770-49f9-88e3-159d06bb56c4)
![1719826296688](https://github.com/Steve-xmh/amll-ttml-tool/assets/50987405/417ca65d-221a-451e-8472-c7748e6c6767)

**Comment by Steve-xmh** [comment]
可以的话，提供一下保存了的TTML文本（可以删除多余的行只保留能被复现的行）

**Comment by ITManCHINA** [comment]
> 可以的话，提供一下保存了的TTML文本（可以删除多余的行只保留能被复现的行）

这边是音乐本体和保存下来的歌词，我转到[蓝奏云](https://itmanchina.lanzouw.com/i1I4m238edef
)上了。歌词部分我截取了从`00:26`开始到`00:50`的部分，标记了`背景人声`的部分都是需要保留`背景人声`和`对唱人声`的设定的。

**Comment by Steve-xmh** [comment]
已经根据情况修正问题，请稍后等待网站更新后再尝试，如果没问题了就可以关闭这个议题了

**Comment by ITManCHINA** [comment]
Bug fixed. Close as Completed.
