### ISSUE TITLE
背景人声

### ISSUE THREAD

**Issue by Y-CIAO** [Steve-xmh/amll-ttml-tool#3]
背景人声会跟在上一行后面，而不是另起一行，而且背景人声歌词大小和其他歌词一样大。
![image](https://github.com/Steve-xmh/amll-ttml-tool/assets/132769718/d55d49be-4eae-46ef-a3aa-3e090993808b)

**Comment by Steve-xmh** [comment]
背景人声通常用在一句主歌词背后一般不做演唱的歌词，如果背景歌词过多密集可能要考虑是否应该使用对唱歌词来代替了
背景人声歌词的限制是 TTML 格式带来的，并非工具

如果你的意思是上一句不是背景人声，而这一句是背景人声但是却按照了普通歌词的方式展示，那有可能是因为你处于对唱歌词的状态，这个应该是 AMLL 插件的问题。

如果需要的话我可以帮你打你需要的歌的歌词，之后可以参考一下类似的歌词的做法。

（就先关闭议题了，问题不出在工具身上，可以在 AMLL 那里创建这样的议题）
