### ISSUE TITLE
[Bug反馈] 从 Lyricify Syllable 导入出现问题

### ISSUE THREAD

**Issue by Seayay** [Steve-xmh/amll-ttml-tool#31]
从 Lyricify Syllable 导入歌词后：

1. ~~部分行的开始时间为 00:00.000~~ 疑似原歌词问题
2. ~~部分文字的开始时间为 00:00.000~~ 疑似原歌词问题
3. 对唱视图、背景人声设置没有被导入 **已成功复现**

示例 Lyricify Syllable 文件: [https://dpaste.org/gqHFP](https://dpaste.org/gqHFP)

**Comment by Steve-xmh** [comment]
请提供原 Lyricify Syllable 歌词文本

**Comment by Seayay** [comment]
#26
