### ISSUE TITLE
Lyricify Syllable 歌词中已存在的时间戳有几率不会覆盖

### ISSUE THREAD

**Issue by tsavpyn** [Steve-xmh/amll-ttml-tool#6]
使用时发现，当歌词过长或某些原因下，一些歌词原有的时间戳不会被新的时间戳覆盖，可能导致以下情况：
`[0]This (0,0)is (0,0)a (0,0)lyrics (120,1230)(130,112300)`
出现这种情况将无法正常将歌词上传到 Lyricify Vault

**Comment by Steve-xmh** [comment]
这个属于打轴问题，使用者需要自行核对单词时间轴，编辑器可以尽量提供一定的警告标识，但是无法自动修复此类打轴时序问题
